version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

workflows:
  deploy:
    jobs:
      - build_and_deploy

jobs:
  build_and_deploy:
    steps:
      - checkout
      - run:
          name: kiem tra source code
          command: ls -la
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key:  AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          arguments: --delete
          from: .
          to: s3://web2.babaucanbiet.com