version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

workflows: 
  version: 2
  dev:
    jobs: 
      - test:
          filters:
            branches:
              ignore: master
      - build_and_deploy:
          requires:
            - test
          bucket: web-dev.web2.babaucanbiet.com
  prod:
    jobs: 
      - test:
          filters:
            branches:
              only: master
      - build_and_deploy:
          requires:
            - test
          bucket: web.web2.babaucanbiet.com


jobs:
  test:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - run:
          name: Test step
          command: |
            echo "Run test command here"
  build_and_deploy:
    parameters:
      bucket:
        type: string
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run:
          name: List files and folder in root of repo
          command: |
            ls -la
      - aws-s3/sync:
          arguments: |
            --delete
          from: ./src
          to: s3://<< parameters.bucket >>
